services:
  - type: web
    name: django-react-fullstack
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend/crowdfind && npm install && npm run build
      xcopy /E /I /Y frontend\crowdfind\build backend\build
    startCommand: cd backend && gunicorn mysite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
