services:
  - type: web
    name: django-react-fullstack
    env: python
    rootDir: backend/crowdfind
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend/crowdfind && npm install && npm run build
      cp -r build ../../backend/crowdfind/build
    startCommand: gunicorn crowdfind.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crowdfind.settings
