# Generated by Django 5.1.6 on 2025-02-14 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdfundingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('company_title', models.CharField(max_length=255)),
                ('estimated_profit', models.FloatField()),
                ('project_picture_link', models.URLField(max_length=255)),
                ('has_opportunity', models.BooleanField()),
                ('crowdfunding_platform_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.crowdfundingplatform', to_field='link')),
            ],
        ),
    ]
