# Generated by Django 5.1.6 on 2025-04-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_warranty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='telegram_link',
            field=models.URLField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_opportunity',
            field=models.BooleanField(default=True),
        ),
    ]
