# Generated by Django 5.1.6 on 2025-05-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_has_warranty_project_telegram_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='crowdfunding_platform_link',
            new_name='crowdfunding_platform',
        ),
    ]
